ui <- fluidPage(
  # Application title
  titlePanel("Correlation between Copy Number and Gene Expression"),
  
  # Sidebar with controls to select the random distribution type
  # and number of observations to generate. Note the use of the br()
  # element to introduce extra vertical spacing
  sidebarPanel(
    fileInput('file2', 'Upload band CNV table generated by preprocessing-CNA-GSEA.R'),
    fileInput('file3', 'Upload GSEA table generated outside of this program.'),
    #fileInput('file4', 'Upload categorical file generated outside of this program.'),
    fileInput('file1', 'Upload correlation table generated by computation-CNA-GSEA.R'),
    #uiOutput("signature"),
    selectInput(inputId = "signature", label = "Select a signature to plot:",
                choices = "Upload a dataset!"),
    uiOutput("band"),
    br(),
    
    sliderInput("n", 
                "Number of observations:", 
                value = 500,
                min = 1, 
                max = 1000)
  ),
  
  # Show a tabset that includes a plot, summary, and table view
  # of the generated distribution
  mainPanel(
    tabsetPanel(
      tabPanel("Plot", plotOutput("plot")), 
      tabPanel("Summary", verbatimTextOutput("summary")), 
      tabPanel("Table", dataTableOutput("table"))
    )
  ),
  mainPanel(
    tags$a(href="http://nickgros.com/shiny.html", "nickgros.com")
  )
)
